application: rics-woven-code-test-2016
version: 1
runtime: python27
threadsafe: true
api_version: 1


handlers:
# Endpoints handler

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: .*
  script: main.app

builtins:
- deferred: on

libraries:
- name: webapp2
  version: "latest"